version: '3.9'

services:
  java_app:
    container_name: java_app
    image: francescoxx/java_app:1.0.0
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5434/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - java_db


  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
